# Generated by Django 4.1 on 2022-08-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=20)),
                ('correo_Electronico', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=20)),
                ('repetir_Contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
