# Generated by Django 4.1 on 2022-08-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Registro',
        ),
    ]
