# Generated by Django 4.1 on 2022-08-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_rename_task_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='contraseña',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='correo_Electronico',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='repetir_Contraseña',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='usuario',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
