# Generated by Django 4.1 on 2022-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_registro_contraseña_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinos', models.CharField(max_length=50)),
                ('terminal', models.CharField(max_length=50)),
                ('fecha_ida', models.CharField(max_length=50)),
                ('fecha_vuelta', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
