# Generated by Django 4.1 on 2022-08-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_opinion_correo_electronico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo_Electronico', models.CharField(max_length=100)),
            ],
        ),
    ]
