# Generated by Django 4.1 on 2022-08-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_recuperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Tarjeta', models.IntegerField(max_length=19)),
                ('nombre_Tarjeta', models.CharField(max_length=50)),
                ('mes_Expiriacion', models.IntegerField(max_length=15)),
                ('anio_Expiracion', models.IntegerField(max_length=5)),
                ('CCV', models.IntegerField(max_length=3)),
            ],
        ),
    ]
