# Generated by Django 4.1 on 2022-08-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_datos_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_tarjeta',
            name='CCV',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datos_tarjeta',
            name='anio_Expiracion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datos_tarjeta',
            name='mes_Expiriacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datos_tarjeta',
            name='numero_Tarjeta',
            field=models.IntegerField(),
        ),
    ]
