# Generated by Django 4.1 on 2022-08-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_alter_datos_tarjeta_ccv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_tarjeta',
            name='numero_Tarjeta',
            field=models.CharField(max_length=19),
        ),
    ]
