# Generated by Django 4.1 on 2022-08-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_alter_datos_tarjeta_numero_tarjeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_tarjeta',
            old_name='mes_Expiriacion',
            new_name='mes_Expiracion',
        ),
    ]
